### ISSUE TITLE
Идея

### ISSUE THREAD

**Issue by Kulichkins** [Kulichkins/text_to_speach#1]
Подготовка темы, обозначение продукта.

**Comment by 3kk327** [comment]
Сверьте готовую программу с изначальным продуктом

**Comment by Kulichkins** [comment]
Крч так как у нас все выполнено по сути щас буду лохматится над установщиком, типо постараюсь создать установщик для нашего приложения exe файл я уже создал но он к сожалению только у меня работает пока не знаю почему. Поэтому пойдем другим путем.
