### ISSUE TITLE
Код

### ISSUE THREAD

**Issue by Kulichkins** [Kulichkins/text_to_speach#4]

**Comment by 3kk327** [comment]
ffffffffffffffffffffffffffffffffffffffffffffffff

**Comment by Kulichkins** [comment]
Добавил тестовый вариант работы нейросетки пока что генерит только файл wav формата буду разбираться как залить в бд завтра

**Comment by Kulichkins** [comment]
если что находится в новой ветке там увидите

**Comment by Kulichkins** [comment]
Настроил начальное взаимодействие с бд тип теперь пользователь может регистрироваться, оставшиеся фичи полетят завтра

**Comment by Kulichkins** [comment]
Добавил регистрацию со всеми проверками а также настроил авторизацию время кушатьб

**Comment by Kulichkins** [comment]
Добавил выгрузку аудио файла в бд отладил процесс авторизации и возможности вывода данных
Завтра буду делать обратный синтез файла с бд
если что это последний коммит в ветке ai_injectet_V1.0 commit : Visual_Ai_Db_...

**Comment by Kulichkins** [comment]
13:47 09.01.2024 Курсовая готова. Полагаю что можно приступать к улучшению

**Comment by 3kk327** [comment]
Отлично, не забывай выполнять коммиты и пожалуйста подписывай их адекватно)

**Comment by 3kk327** [comment]
Так же если у нас в целом курсач готов сегодня собираемся, будешь показывать работу, над улучшениями подумаю.

**Comment by Kulichkins** [comment]
Крч улучшение имба

**Comment by Kulichkins** [comment]
вроде все готово никак нельзя ввести лишнего и вызвать ошибку у приложения вопрос только в производительности.

**Comment by Kulichkins** [comment]
выгружаю в гитхаб и курсач готов по сути
