### ISSUE TITLE
Проектировка

### ISSUE THREAD

**Issue by 3kk327** [Kulichkins/text_to_speach#5]

**Comment by 3kk327** [comment]
От проектировщика жду:
1)Данные по заданию UML Диаграммы
2)Обоснованную архитектуру продукта
3)Написать требования к системному ПО 
4)Концепт БД
5)Отчитываться о выполнении и выгрузке файлов здесь, в issues: Проектировка

**Comment by 3kk327** [comment]
Также если сегодня убедимся в готовности проекта нужно будет подготовить план по разработке улучшения проекта для программиста.

**Comment by Dashttps** [comment]
В ветке main была создана папка "Projectirovchik" внутри которой для каждой диаграммы также были созданы отдельные папки.
Добавлены следующие диаграммы:
1) Архитектурная диаграмма 
2) Функциональная диаграмма UML
3) Диаграмма последовательности UML
Также была добавлена концептуальная модель БД, текстовый файл с архитектурой продукта и текстовый файл, содержащий требования к системному ПО.

**Comment by Dashttps** [comment]
В папку "Projectirovchik" в ветке main добавила вордовский документ с разделом проектирования для ПЗ.

**Comment by Dashttps** [comment]
В ходе контрольной проверки курсовой работы вместе с остальными участниками команды были исправлены некоторые диаграммы, окончательные варианты диаграмм внесены в папку "Projectirovchik".
