### ISSUE TITLE
Новое самое крутое приложение теперь доступно на всех ПК

### ISSUE THREAD

**Issue by Kulichkins** [Kulichkins/text_to_speach#7]

**Comment by Kulichkins** [comment]
Вчера мы смогли скомпелировать наш код и создать приложение а сегодня сделали уже установщик и теперь каждый пользователь у которого есть pgAdmin сможет развернуть бд и использовать нашу прогу

**Comment by Kulichkins** [comment]
Имба товарищи

**Comment by 3kk327** [comment]
УДАЧИ НАМ НА ЗАЩИТЕ!! ВСЕ БОЛЬШИЕ МОЛОДЦЫ)))))))00
